Items_in_front_of_Simple_Background_Test_Video_Data
net=load('-mat','Items_in_front_of_Simple_Background'); 
input=load('-mat','Items_in_front_of_Simple_Background_input'); 
output=load('-mat','Items_in_front_of_Simple_Background_output'); 
view(net.net);
inputtest=mapminmax('apply',Feature,input.inputps);
outputtest=sim(net.net,inputtest);
MOS_pre=mapminmax('reverse',outputtest,output.outputps);
plot(MOS,MOS_pre,'o')
Pearson=corr(MOS',MOS_pre','type','Pearson')
Spearman=corr(MOS',MOS_pre','type','Spearman')